name: Example CMake

on:
  push:
      branches:
      - master
  pull_request:
  #schedule:
  #  - cron: '0 0 * * 3'
  workflow_dispatch:

jobs:

  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { icon: '⬛', sys: mingw32 }
          - { icon: '🟦', sys: mingw64 }
          - { icon: '🟨', sys: ucrt64  } # Experimental!
          - { icon: '🟧', sys: clang64 } # Experimental!
    name: 🚧${{ matrix.icon }} ${{ matrix.sys }}
    defaults:
      run:
        shell: msys2 {0}
    steps:

    - name: '🧰 Checkout'
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: '${{ matrix.icon }} Setup MSYS2'
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.sys}}
        update: true
        install: >-
          git
          make
        pacboy: >-
          toolchain:p
          cmake:p
          qt5-static:p
          ninja:p
    - name: '🚧 Build TOOL'
      run: |
        /${{matrix.sys}}/qt5-static/bin/qmake
        make
    - uses: actions/upload-artifact@v3
      with:
        name: bin
        path: |
          release/Servoterm.exe
